### ISSUE TITLE
Potential UB in Demo due to unaligned access

### ISSUE THREAD

**Issue by Shadlock0133** [logicomacorp/pulsejet#1]
While I was porting pulsejet to Rust ([here](https://github.com/Shadlock0133/pulsejet-rs)), I'd some problems while testing original code.

I've setup C++ code to compile both original and my code to compare output, but I was getting segfaults. My C++ test code was partially copied from Demo.cpp, and I've noticed that here: https://github.com/logicomacorp/pulsejet/blob/ec73d19ccb71ff05b2122e258fe4b7b16e55fb53/demo/Demo.cpp#L102 there is a pointer cast from bytes to floats. I think that in C++ casting pointer to bigger alignment (without checking if it's correctly aligned) is UB, 'tho I haven't thoroughly tested if that was causing the segfaults (I ended up just translating code to safe rust and manually checking if output sounds good).

It could probably be fixed by adding `ReadFileAsFloats` function that loads file directly into `vector<float>`.

**Comment by yupferris** [comment]
Nice catch, yeah this is likely a bug. Feel free to submit a PR for it ^^
